# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ff3eaf32077a26a901472ecaf25c5ec5f7d76f006e1673a42895c1b98f154db1e7f9e3e74ffd79b161078a0f4d83508e124302ee3d5f3e84dd8ae3ff4c9beb8

test:
  secret_key_base: 7d3939b9431a03192c13c6f55a9d02c5f9d795573cc1a4fa580ccea16b8b5d8627b7cda5275848d7169e280b60afcea530385a54d25b41e3332002f78d9b6d24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
